title: "Event Store Documentation"
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments

top_level_sections:
    - Introduction
    - Server
    - .NET API
    - HTTP API

latest_versions:
    server: 3.3.0
    dotnet-api: 3.0.2
    http-api: 3.0.3

defaults:
    -
        scope:
            path: ""
        values:
            exclude_from_sidebar: false
            layout: "docs"
            pinned: false
