### YamlMime:ManagedReference
items:
- uid: EventStore.Transport.Http.ProxyHeaderValues
  commentId: T:EventStore.Transport.Http.ProxyHeaderValues
  id: ProxyHeaderValues
  parent: EventStore.Transport.Http
  children:
  - EventStore.Transport.Http.ProxyHeaderValues.XForwardedProtoHttp
  - EventStore.Transport.Http.ProxyHeaderValues.XForwardedProtoHttps
  langs:
  - csharp
  - vb
  name: ProxyHeaderValues
  nameWithType: ProxyHeaderValues
  fullName: EventStore.Transport.Http.ProxyHeaderValues
  type: Class
  source:
    remote:
      path: src/EventStore.Transport.Http/ProxyHeaders.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: ProxyHeaderValues
    path: ../EventStore/src/EventStore.Transport.Http/ProxyHeaders.cs
    startLine: 10
  assemblies:
  - EventStore.Transport.Http
  namespace: EventStore.Transport.Http
  syntax:
    content: 'public static class ProxyHeaderValues : object'
    content.vb: >-
      Public Module ProxyHeaderValues
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: EventStore.Transport.Http.ProxyHeaderValues.XForwardedProtoHttp
  commentId: F:EventStore.Transport.Http.ProxyHeaderValues.XForwardedProtoHttp
  id: XForwardedProtoHttp
  parent: EventStore.Transport.Http.ProxyHeaderValues
  langs:
  - csharp
  - vb
  name: XForwardedProtoHttp
  nameWithType: ProxyHeaderValues.XForwardedProtoHttp
  fullName: EventStore.Transport.Http.ProxyHeaderValues.XForwardedProtoHttp
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Http/ProxyHeaders.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: XForwardedProtoHttp
    path: ../EventStore/src/EventStore.Transport.Http/ProxyHeaders.cs
    startLine: 12
  assemblies:
  - EventStore.Transport.Http
  namespace: EventStore.Transport.Http
  syntax:
    content: public const string XForwardedProtoHttp = null
    return:
      type: System.String
    content.vb: Public Const XForwardedProtoHttp As String = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: EventStore.Transport.Http.ProxyHeaderValues.XForwardedProtoHttps
  commentId: F:EventStore.Transport.Http.ProxyHeaderValues.XForwardedProtoHttps
  id: XForwardedProtoHttps
  parent: EventStore.Transport.Http.ProxyHeaderValues
  langs:
  - csharp
  - vb
  name: XForwardedProtoHttps
  nameWithType: ProxyHeaderValues.XForwardedProtoHttps
  fullName: EventStore.Transport.Http.ProxyHeaderValues.XForwardedProtoHttps
  type: Field
  source:
    remote:
      path: src/EventStore.Transport.Http/ProxyHeaders.cs
      branch: docs
      repo: https://github.com/ChrisChinchilla/EventStore.git
    id: XForwardedProtoHttps
    path: ../EventStore/src/EventStore.Transport.Http/ProxyHeaders.cs
    startLine: 13
  assemblies:
  - EventStore.Transport.Http
  namespace: EventStore.Transport.Http
  syntax:
    content: public const string XForwardedProtoHttps = null
    return:
      type: System.String
    content.vb: Public Const XForwardedProtoHttps As String = Nothing
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: EventStore.Transport.Http
  commentId: N:EventStore.Transport.Http
  isExternal: false
  name: EventStore.Transport.Http
  nameWithType: EventStore.Transport.Http
  fullName: EventStore.Transport.Http
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
